# 0. GPT From Scratch

이 노트북은 GPT 논문을 기반으로 간단한 클론코딩을 통해 세익스피어풍의 작품을 생성해내는 언어 모델을 구현한 것입니다.

1. dataset:  tiny shakespere dataset 
2. tokenization : character-level 

언어 모델의 학습 방법론과 트랜스포머 구조에 대한 아주 기초적인 이해를 보유하고 있다고 가정하고 작성을 진행하겠습니다.

# 1. Dataset Preperation & Analysis

In [76]:
with open('./datas/input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [77]:
# 데이터셋에 대한 여러 가지를 확인해봅니다. 
print("데이터셋의 총 길이:", len(text))
print("데이터셋의 첫 1000자:\n==============================\n" + text[:1000] + "==============================" )

데이터셋의 총 길이: 1115394
데이터셋의 첫 1000자:
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for 

# 2. Tokenizing & Encoding Text - chararcter level

- 간단하게 character level로 토큰화 및 인코딩하기로 결정함. 
- 구현이 간편하지만 인코딩된 토큰이 의미를 담아내지 못하므로
- 모델 성능은 상당히 낮을 것으로 예상됨. 

In [78]:
# Dataset의 모든 character 추출 및 등장 빈도만큼 오름차순 정렬
# character-level이므로 vocab은 등장한 모든 문자의 모음이 됩니다. 
chars = sorted(list(set(text)))
vocab_size = len(chars)

print("vocab:", ''.join(chars))
print("vocab size:", vocab_size)

vocab: 
 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
vocab size: 65


In [79]:
# 문자 하나 당 번호 하나를 매깁니다. 
stoi = {ch:i for i, ch in enumerate(chars)}
itos = {i:ch for i, ch in enumerate(chars)}

# 문자열과 벡터를 오가는 인코딩/디코딩 함수를 만들어줍니다. 
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print("========== 예시 ==========")
print(encode("hi there!"))
print(decode(encode("What's your name?")))

========== 예시 ==========
[46, 47, 1, 58, 46, 43, 56, 43, 2]
What's your name?


In [80]:
# 전체 데이터셋 인코딩

# 위 인코더로 text를 인코딩한 뒤 torch tensor 형태로 전체 데이터를 준비해둡니다. 
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print("data의 shape:", data.shape)
print("data의 dtype:", data.dtype)
# print(data[:1000])

data의 shape: torch.Size([1115394])
data의 dtype: torch.int64


# 3. Train / Validation / Test Split

In [81]:
# train과 test data를 분리한다.
# 비율은 약 10%로 정함.
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

이 데이터들을 "batch * context length" shape의 tensor 단위로 묶어낸다. 

In [82]:
# 모델의 context window size를 정한다. 
context_length = 8
print(train_data[:context_length + 1])

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])


In [83]:
# 예시
x = train_data[:context_length]
y = train_data[1: context_length + 1]
for i in range(context_length):
    context = x[:i + 1]
    target = y[i]
    print(f'input이 {context}일 때의 target: {target}')

input이 tensor([18])일 때의 target: 47
input이 tensor([18, 47])일 때의 target: 56
input이 tensor([18, 47, 56])일 때의 target: 57
input이 tensor([18, 47, 56, 57])일 때의 target: 58
input이 tensor([18, 47, 56, 57, 58])일 때의 target: 1
input이 tensor([18, 47, 56, 57, 58,  1])일 때의 target: 15
input이 tensor([18, 47, 56, 57, 58,  1, 15])일 때의 target: 47
input이 tensor([18, 47, 56, 57, 58,  1, 15, 47])일 때의 target: 58


In [84]:
# 모델의 batch size를 정한다. 
torch.manual_seed(1337)
batch_size = 4
context_length = 8

def get_batch(split):
    '''
    get_batch: 

    split: 어떤 데이터에 대한 batch를 불러올 건지 결정. 
    'train'인 경우 train_data에 대해서, 아닌 경우 val_data에 대해서 가져옴.
    '''
    # 데이터 불러오기
    data = train_data if split == 'train' else val_data 

    # batch size 개수의 랜덤한 offset 생성. 
    ix = torch.randint(len(data) - context_length, (batch_size,)) 

    # 랜덤 생성한 시작지점 ix에 대한 x, y 가져오기
    x = torch.stack([data[i : i + context_length] for i in ix])
    y = torch.stack([data[i + 1 : i + context_length + 1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('입력: ')
print(xb.shape)
print(xb)

for l in xb.tolist():
    print(decode(l))
print("========================================")
print('target: ')
print(yb.shape)
print(yb)

for l in yb.tolist():
    print(decode(l))

print('========================================')

for btch in range(batch_size):
    for ctxt in range(context_length):
        context = xb[btch, : ctxt + 1]
        target = yb[btch, ctxt]
        print(f'입력이 {context.tolist()}일 때 target: {target}')

입력: 
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
Let's he
for that
nt that 
MEO:
I p
target: 
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
et's hea
or that 
t that h
EO:
I pa
입력이 [24]일 때 target: 43
입력이 [24, 43]일 때 target: 58
입력이 [24, 43, 58]일 때 target: 5
입력이 [24, 43, 58, 5]일 때 target: 57
입력이 [24, 43, 58, 5, 57]일 때 target: 1
입력이 [24, 43, 58, 5, 57, 1]일 때 target: 46
입력이 [24, 43, 58, 5, 57, 1, 46]일 때 target: 43
입력이 [24, 43, 58, 5, 57, 1, 46, 43]일 때 target: 39
입력이 [44]일 때 target: 53
입력이 [44, 53]일 때 target: 56
입력이 [44, 53, 56]일 때 target: 1
입력이 [44, 53, 56, 1]일 때 target: 58
입력이 [44, 53, 56, 1, 58]일 때 target: 46
입력이 [44, 53, 56, 1, 58, 46]일 때 target: 39
입력이 [44, 53, 56, 1, 58, 46, 39]일 때 target: 58
입력이 [44, 53,

- get_batch 함수를 통해 context_length 길이의 '문장'을(정확히 말하면 문장은 아님) batch_size 개만큼 가져옴.
- 즉, batch_size x context_length shape의 tensor x, y를 구성.
- x는 주어진 context, y는 주어진 context에 대한 정답(target)

In [85]:
print(xb)

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


# 4. Model 정의

### 1. Bigram Language Model

In [86]:
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)

class BigramLanguageModelVer1(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()

        # 토큰 임베딩 테이블 정의
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets):

        '''
        idx: (B, T) tensor. x가 들어갈 위치(input)
        targets: (B, T) tensor. y가 들어갈 위치(target)
        logits: (B, T, C) tensor. 여기서 C는 Channel로, 여기서는 vocab_size를 나타냄. 

        즉, C개의 문자가 각 (B, T)의 예측 target에 해당할 각각의 logit을 나타낸 것. 
        '''
        
        # 토큰 임베딩 테이블을 lookup하여 logit 구함
        logits = self.token_embedding_table(idx)

        # 구한 logit과 target을 비교하여 loss 계산

        # 차원을 맞추기 위한 작업
        # loss를 계산하려면 B, C, T의 shape이어야 함. 
        # logit과 target을 모두 B*T로 차원 축소해서 길게 늘린 뒤 비교
        # 자세한 건 pytorch 공식문서 읽어보기!!!! 
        B, T, C = logits.shape
        logits = logits.view(B * T, C)
        targets = targets.view(B*T) # -1
        loss = F.cross_entropy(logits, targets) # Negative Log Likelihood 사용 
        # -ln(1/65) ~= 4.17

        return logits, loss
    
m = BigramLanguageModelVer1(vocab_size)
logits, loss = m(xb, yb) # forward 함수 실행됨
print(logits.shape)
print(loss)

torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)


이 모델은 각 토큰끼리의 정보 교환(어텐션, 피드 포워딩 등)을 일절 하지 않은 채 '현재 해당하는 토큰 임베딩값'만으로 다음 토큰을 예측하는 모델임.

랜덤 초기화된 임베딩 테이블을 그대로 사용해 예측을 수행했기 때문에 단순 찍기에 달하는 성능을 보인다... (당연한 게 이 모델이 단순 찍기 모델이기 때문이다)

찍기의 loss 기댓값은 -ln(1/65) ~= 4.17이지만 우리의 모델은 4.87을 보이는 중. 

이제 이 모델로 생성을 해보자!

### BigramLanguageModel - generate 추가 버전

In [87]:
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()

        # 토큰 임베딩 테이블 정의
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    # target 여부를 optional로 두어야!
    def forward(self, idx, targets=None):

        '''
        idx: (B, T) tensor. x가 들어갈 위치(input)
        targets: (B, T) tensor. y가 들어갈 위치(target)
        logits: (B, T, C) tensor. 여기서 C는 Channel로, 여기서는 vocab_size를 나타냄. 

        즉, C개의 문자가 각 (B, T)의 예측 target에 해당할 각각의 logit을 나타낸 것. 
        '''
        
        # 토큰 임베딩 테이블을 lookup하여 logit 구함
        logits = self.token_embedding_table(idx)

        if targets is None:
            loss = None
        else:
            # 구한 logit과 target을 비교하여 loss 계산

            # 차원을 맞추기 위한 작업
            # loss를 계산하려면 B, C, T의 shape이어야 함. 
            # logit과 target을 모두 B*T로 차원 축소해서 길게 늘린 뒤 비교
            # 자세한 건 pytorch 공식문서 읽어보기!!!! 
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B*T) # -1
            loss = F.cross_entropy(logits, targets) # Negative Log Likelihood 사용 
            # -ln(1/65) ~= 4.17

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        '''
        idx: x
        max_new_tokens: 생성 가능한 최대 토큰 개수수
        '''

        for _ in range(max_new_tokens):
            
            # forward로 logit과 loss 계산
            logits, loss = self(idx)

            # 각 batch의 마지막 문자에 대한 예측만 취함(Bi-gram이기 때문!)
            logits = logits[:, -1, :] # (B, T, C) -> (B, C)

            # 여기서 들 수 있는 의문점: 어차피 마지막 문자에 대한 예측만 볼 거면서 왜 
            # 계속 늘어나는 idx를 그대로 forward에 넣고 있을까?
            # 나중에 모델을 N-gram으로 확장할 때 함수의 형태를 최대한 일관되게 하려고 함
            # 연산은 비효율적이지만 공부하는데에는 이렇게 하는게 좋을 듯. 

            # Softmax 거쳐서 확률 계산
            probs = F.softmax(logits, dim = -1) # (B, C)

            # 분포에 따라 추출(예측 생성성)
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)

            # 각 batch에 대한 예측 결과를 x의 맨 끝에 append
            idx = torch.cat((idx, idx_next), dim = 1) # (B, T + 1)
        
        # 위 loop가 돌면서 idx는 (B, T + 1), (B, T + 2), ... , (B, T + max_new_tokens)의 shape이 됨.
        return idx
    
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb) # forward 함수 실행됨
print(logits.shape)
print(loss)

torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)


In [88]:
idx = torch.zeros((1, 1), dtype=torch.long) # 0에서 생성 시작. 
# 0은 \n 문자임!
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist()))


Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


역시 개판임을 볼 수 있다!
이제 이 모델을 학습시켜 보자!


In [89]:
# optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [98]:
batch_size = 32
for steps in range(10000):
    xb, yb = get_batch('train')

    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.514219284057617


In [100]:
print(decode(m.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=400)[0].tolist()))


HAnour w m, f m outr I omounour.
An:
CEDou chean' th lly, t pofe inorir t say ithelin u!

mmf ar thirt youd'duretherk w t tese toputha s ir morovesellaisa RYopur.

N:
NRLLAny!
Youse ortherid argareswors ltour. hothee dg tinere
My. t otyoo 'd t mavim'llisqu'ssby hay trd f t AS:
pr bu amees, tl hopu it g ans kn:
MESedigrves st ceary;
Ana or: hind ould
HAy fonth ard m:
Pe VIEN tway h awinghem lt stut


오... 이제 좀 뭔가 따라하려는 흔적이 보이기 시작한다!

여기까지 내용을 bigram.py로 저장